### ISSUE TITLE
How to add multiple keys for the same user

### ISSUE THREAD

**Issue by aviralg** [PRL-PRG/prg-cluster-config#10]
I would like to be able to access `prl3` from two locations. How do I specify multiple ssh keys?

**Comment by fikovnik** [comment]
This is not possible atm, but should not be difficult with a loop. Out of curiosity, why don't you have the same key in multiple machines?

**Comment by aviralg** [comment]
I didn't do it because the key as of now uniquely identifies me and the machine from which I am logging. I guess there is no good reason at the moment for the machine to be part of the key.
Its better to keep the setup simple. So don't add support for multiple keys. I will copy over the same key to the other machine.
